// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-IhYLgA-f1Sj7mrbLps6g0UqSX_l3vD0',
    appId: '1:234767349779:web:2f7c3bbf526f71e1db67e6',
    messagingSenderId: '234767349779',
    projectId: 'examapp-c91d4',
    authDomain: 'examapp-c91d4.firebaseapp.com',
    storageBucket: 'examapp-c91d4.firebasestorage.app',
    measurementId: 'G-3PTHX78RT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKkLTU9I-sdvC3zwUjKsn8lDz2cYxeydM',
    appId: '1:234767349779:android:061bc4ad59f555a8db67e6',
    messagingSenderId: '234767349779',
    projectId: 'examapp-c91d4',
    storageBucket: 'examapp-c91d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn-kjT86p1L_PqyopNHiH8Ib2v0vrKqbI',
    appId: '1:234767349779:ios:420de75ba8ecef9bdb67e6',
    messagingSenderId: '234767349779',
    projectId: 'examapp-c91d4',
    storageBucket: 'examapp-c91d4.firebasestorage.app',
    iosBundleId: 'com.example.anotherExamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn-kjT86p1L_PqyopNHiH8Ib2v0vrKqbI',
    appId: '1:234767349779:ios:420de75ba8ecef9bdb67e6',
    messagingSenderId: '234767349779',
    projectId: 'examapp-c91d4',
    storageBucket: 'examapp-c91d4.firebasestorage.app',
    iosBundleId: 'com.example.anotherExamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-IhYLgA-f1Sj7mrbLps6g0UqSX_l3vD0',
    appId: '1:234767349779:web:c53cc022edff31e8db67e6',
    messagingSenderId: '234767349779',
    projectId: 'examapp-c91d4',
    authDomain: 'examapp-c91d4.firebaseapp.com',
    storageBucket: 'examapp-c91d4.firebasestorage.app',
    measurementId: 'G-HLL85K0KD0',
  );
}
